# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - BC-PF-Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend_old/**"
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set working directory to backend folder
        working-directory: backend_old
        run: echo "Using backend_old directory"
        
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        working-directory: backend_old
        run: |
          python -m pip install --upgrade pip
          ls -la       # show files
          pip install -r requirements.txt

      - name: Zip backend folder for deployment
        run: |
          cd backend_old
          zip -r ../backend.zip .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_47C7C043017642DFA6FBD2B27CABA7F1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F207DA8E264948DFA59948D302CA06EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DDFDCBCF280647A78A578C8EDF3783C0 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'BC-PF-Backend'
          package: backend.zip

          

