# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - BD-PF-UI

on:
  push:
    branches:
      - main
    paths:
      - "bc_pf_frontend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install frontend dependencies
        working-directory: bc_pf_frontend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip frontend folder for deployment
        run: |
          cd bc_pf_frontend
          zip -r ../frontend.zip .
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CD95935C2BC149D7B2A2348C8CCDF690 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_115AB89816E34A2AB8AAADD90D35DCEB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD8665D4778B4E49AE2F7DA625C29629 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'BD-PF-UI'
          package: frontend.zip

          
